/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-01-08 01:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/pages/common/rs_js.jsp", Long.valueOf(1546594877000L));
    _jspx_dependants.put("/WEB-INF/pages/common/rs_css.jsp", Long.valueOf(1546594877000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<title>用户列表</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("\n");
      out.write("<!-- basic styles -->\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/dataTables.bootstrap.css\"\n");
      out.write("\trel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/font-awesome.min.css\" />\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/ace.min.css\" />\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/ace-rtl.min.css\" />\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/ace-skins.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/mashen/css/default.css\" />\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/ace-extra.min.js\"></script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body style=\"width:98%\">\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-default\" id=\"search\">查询</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"table-responsive\">\n");
      out.write("\t\t\t\t<table id=\"mydatatables\"\n");
      out.write("\t\t\t\t\tclass=\"table table-striped table-bordered table-hover\">\n");
      out.write("\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<th class=\"center\"><label> <input type=\"checkbox\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ace\" /> <span class=\"lbl\"></span>\n");
      out.write("\t\t\t\t\t\t\t</label></th>\n");
      out.write("\t\t\t\t\t\t\t<th>账号</th>\n");
      out.write("\t\t\t\t\t\t\t<th>用户名</th>\n");
      out.write("\t\t\t\t\t\t\t<th>手机号码</th>\n");
      out.write("\t\t\t\t\t\t\t<th>所属部门</th>\n");
      out.write("\t\t\t\t\t\t\t<th>操作</th>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</thead>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");
      out.write("\n");
      out.write("\t<!-- basic scripts -->\n");
      out.write("\t<!--[if !IE]> -->\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/jquery-2.0.3.min.js\"></script>\n");
      out.write("\t<!-- <![endif]-->\n");
      out.write("\t<!--[if IE]>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/jquery-1.10.2.min.js\"></script>\n");
      out.write("\t<![endif]-->\n");
      out.write("\t<!--[if !IE]> -->\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\twindow.jQuery\n");
      out.write("\t\t\t\t|| document\n");
      out.write("\t\t\t\t\t\t.write(\"<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/jquery-2.0.3.min.js'>\"\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<\" + \"/script>\");\n");
      out.write("\t</script>\n");
      out.write("\t<!-- <![endif]-->\n");
      out.write("\t<!--[if IE]>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("    window.jQuery || document.write(\"<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/jquery-1.10.2.min.js'>\" + \"<\" + \"/script>\");\n");
      out.write("\t</script>\n");
      out.write("\t<![endif]-->\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tif (\"ontouchend\" in document)\n");
      out.write("\t\t\tdocument\n");
      out.write("\t\t\t\t\t.write(\"<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/jquery.mobile.custom.min.js'>\"\n");
      out.write("\t\t\t\t\t\t\t+ \"<\" + \"/script>\");\n");
      out.write("\t</script>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/typeahead-bs2.min.js\"></script>\n");
      out.write("\t<!-- page specific plugin scripts -->\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/jquery.dataTables.min.js\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/jquery.dataTables.bootstrap.js\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/dataTables.bootstrap.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t<!-- ace scripts -->\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/ace-elements.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/ace.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/handlebars.min.js\"></script>\n");
      out.write("\t<!-- inline scripts related to this page -->");
      out.write("\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\n");
      out.write("\t\tjQuery(function($) {\n");
      out.write("\t\t\t//$.fn.dataTable.ext.errMode=\"none\";\n");
      out.write("\t\t\t/* $.fn.dataTable.ext.errMode = function(s,h,m){\n");
      out.write("\t\t\t\talert(s);\n");
      out.write("\t\t\t\talert(h);\n");
      out.write("\t\t\t\talert(m);\n");
      out.write("\t\t\t} */\n");
      out.write("\t\t\t/* mydatatables = $('#mydatatables').on('error.dt',\n");
      out.write("\t\t\t\t\tfunction ( e, settings, techNote, message ) {\n");
      out.write("\t\t        \t\tconsole.log(e);\n");
      out.write("\t\t        \t\tconsole.log(settings);\n");
      out.write("\t\t        \t\tconsole.log(techNote);\n");
      out.write("\t\t        \t\tconsole.log(message);\n");
      out.write("\t\t    \t\t}).DataTable */\n");
      out.write("\t\t    \t\t\n");
      out.write("\t\t\tmydatatables = $('#mydatatables').DataTable(\n");
      out.write("\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\"lengthMenu\" : [ [ 8, 10, 20, 50, 1000 ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t[ 8, 10, 20, 50, \"All\" ] ],\n");
      out.write("\t\t\t\t\t\t\t\t\"pageLength\" : 8,\n");
      out.write("\t\t\t\t\t\t\t\t\"searching\" : true,\n");
      out.write("\t\t\t\t\t\t\t\t\"ordering\" : true,\n");
      out.write("\t\t\t\t\t\t\t\t\"processing\" : true,\n");
      out.write("\t\t\t\t\t\t\t\t\"serverSide\" : true,\n");
      out.write("\t\t\t\t\t\t\t\t\"autoWidth\" : false,\n");
      out.write("\t\t\t\t\t\t\t\t\"dom\": '<\"top\"f >rt<\"bottom\"ilp><\"clear\">',//dom定位\n");
      out.write("\t\t\t\t\t\t\t    \"dom\": 'tiprl',//自定义显示项\n");
      out.write("\t\t\t\t\t\t\t\t//跟数组下标一样，第一列从0开始，这里表格初始化时，\n");
      out.write("\t\t\t\t\t\t\t\t//第四列默认降序\n");
      out.write("\t\t\t\t\t\t\t\t\"order\" : [ [ 6, \"desc\" ] ],\n");
      out.write("\t\t\t\t\t\t\t\t\"ajax\" : {\n");
      out.write("\t\t\t\t\t\t\t\t\t\"url\" : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/rest/doSearch.action\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\"type\" : \"POST\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\"data\" : function(pdata) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t/* pdata.search = {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"value\" : $(\"#searchvalue\").val(),\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"regex\" : \"false\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}; */\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpdata.searchColumns={\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"NameLike\":$(\"#searchName\").val(),\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"AccountEqualTo\":$(\"#searchAccount\").val(),\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"PhoneEqualTo\":$(\"#searchPhone\").val(),\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar data = JSON.stringify(pdata);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn data;\n");
      out.write("\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\tdataType : \"json\",\n");
      out.write("\t\t\t\t\t\t\t\t\tprocessData : false,\n");
      out.write("\t\t\t\t\t\t\t\t\tcontentType : 'application/json;charset=UTF-8',\n");
      out.write("\t\t\t\t\t\t\t\t\terror:function(data,e){\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(e);\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(data);\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\"columns\" : [ {\n");
      out.write("\t\t\t\t\t\t\t\t\t\"data\" : \"id\"\n");
      out.write("\t\t\t\t\t\t\t\t}, {\n");
      out.write("\t\t\t\t\t\t\t\t\t\"data\" : \"name\"\n");
      out.write("\t\t\t\t\t\t\t\t}, {\n");
      out.write("\t\t\t\t\t\t\t\t\t\"data\" : \"salt\"\n");
      out.write("\t\t\t\t\t\t\t\t}, {\n");
      out.write("\t\t\t\t\t\t\t\t\t\"data\" : \"password\"\n");
      out.write("\t\t\t\t\t\t\t\t}, {\n");
      out.write("\t\t\t\t\t\t\t\t\t\"data\" : \"score\"\n");
      out.write("\t\t\t\t\t\t\t\t}, {\n");
      out.write("\t\t\t\t\t\t\t\t\t\"data\" : \"sex\"\n");
      out.write("\t\t\t\t\t\t\t\t}, {\n");
      out.write("\t\t\t\t\t\t\t\t\t\"data\" : \"ctime\",//默认排序字段\n");
      out.write("\t\t\t\t\t\t\t\t\t\"visible\" : false\n");
      out.write("\t\t\t\t\t\t\t\t}],\n");
      out.write("\t\t\t\t\t\t\t\t\"columnDefs\" : [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"render\" : function(data, type, row) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn '<div class=\"checkbox\"><label><input type=\"checkbox\" value=\"'+data+'\"></label></div>';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"targets\" : 0\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"render\" : function(data, type, row) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//row.account\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn '<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/edit.action?id='+data+'\" class=\"tooltip-success\" data-rel=\"tooltip\" title=\"Edit\"><span class=\"green\"><i class=\"icon-edit bigger-120\"></i></a>&nbsp;&nbsp;'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+'<a href=\"javascript:void(0)\" onclick=\"del(\\''+data+'\\')\" class=\"tooltip-error\" data-rel=\"tooltip\" title=\"Delete\"><span class=\"red\"><i class=\"icon-trash bigger-120\"></i></a>';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"targets\" : 5\n");
      out.write("\t\t\t\t\t\t\t\t\t\t} ],\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\"language\" : {\n");
      out.write("\t\t\t\t\t\t\t\t\t\"url\" : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/language/zh_CN.txt\"\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t$(\"#search\").click(function() {\n");
      out.write("\t\t\t\t/* var args = mydatatables.ajax.params(); */\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tmydatatables.ajax.reload();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(\"#searchvalue\").keydown(function(e) {\n");
      out.write("\t\t\t\tif(e.keyCode==13){\n");
      out.write("\t\t\t\t\tmydatatables.ajax.reload();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t//全选\n");
      out.write("\t\t\t$('table th input:checkbox').on(\n");
      out.write("\t\t\t\t\t'click',\n");
      out.write("\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\tvar that = this;\n");
      out.write("\t\t\t\t\t\t$(this).closest('table').find(\n");
      out.write("\t\t\t\t\t\t\t\t'tr > td:first-child input:checkbox').each(\n");
      out.write("\t\t\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\t\tthis.checked = that.checked;\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).closest('tr').toggleClass(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'selected');\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\tfunction del(id){\n");
      out.write("\t\t\tif(window.confirm(\"你确定要删除？\")){\n");
      out.write("\t\t\t\t\t$.getJSON(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/doDel.action?id=\"+id,\n");
      out.write("\t\t\t\t\t\t\t\tfunction(data){\n");
      out.write("\t\t\t\t\t\t\t\t\tif(data.status==1){\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmydatatables.ajax.reload();\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(data.msg);\n");
      out.write("\t\t\t\t\t\t\t\t    }\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
